name: basic_ui_impl_first_task
description: The first task in UI implementation
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.7.0
  flutter_svg_icons: ^0.0.1+3
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/pictures/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Italic.ttf
          style: italic
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700

#  fonts:
#    - family: Pacifico
#      fonts:
#        - asset: fonts/Pacifico-Regular.ttf
#
#    - family: Source Sans Pro
#      fonts:
#        - asset: fonts/SourceSansPro-Regular.ttf
